// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: app.proto

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	app.proto

It has these top-level messages:
	Ping
	Pong
*/
package app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AppService service

type AppService interface {
	// start ping
	StartPing(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error)
}

type appService struct {
	c    client.Client
	name string
}

func NewAppService(name string, c client.Client) AppService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "app"
	}
	return &appService{
		c:    c,
		name: name,
	}
}

func (c *appService) StartPing(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error) {
	req := c.c.NewRequest(c.name, "AppService.StartPing", in)
	out := new(Pong)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppService service

type AppServiceHandler interface {
	// start ping
	StartPing(context.Context, *Ping, *Pong) error
}

func RegisterAppServiceHandler(s server.Server, hdlr AppServiceHandler, opts ...server.HandlerOption) error {
	type appService interface {
		StartPing(ctx context.Context, in *Ping, out *Pong) error
	}
	type AppService struct {
		appService
	}
	h := &appServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AppService{h}, opts...))
}

type appServiceHandler struct {
	AppServiceHandler
}

func (h *appServiceHandler) StartPing(ctx context.Context, in *Ping, out *Pong) error {
	return h.AppServiceHandler.StartPing(ctx, in, out)
}
